nome=input('Qual é o teu nome? ')
print('Bem-vindo(a) {:20}!'.format(nome))
print('Bem-vindo(a) {:>20}!'.format(nome))
print('Bem-vindo(a) {:<20}!'.format(nome))
print('Bem-vindo(a) {:^20}!'.format(nome))
print('Bem-vindo(a) {:=^20}!'.format(nome))